version: '2.1'
services:
  config:
    env_file:
      - .env
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWOR
    image: sqshq/piggymetrics-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

 
